<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
 <head>
  <meta http-equiv="content-type" content="text/html; charset=UTF-8">
  <title>Les exceptions</title>
<link media="all" rel="stylesheet" type="text/css" href="styles/03e73060321a0a848018724a6c83de7f-theme-base.css" />
<link media="all" rel="stylesheet" type="text/css" href="styles/03e73060321a0a848018724a6c83de7f-theme-medium.css" />

 </head>
 <body class="docs"><div class="navbar navbar-fixed-top">
  <div class="navbar-inner clearfix">
    <ul class="nav" style="width: 100%">
      <li style="float: left;"><a href="language.errors.php7.html">« Les Erreurs en PHP 7</a></li>
      <li style="float: right;"><a href="language.exceptions.extending.html">Exceptions &eacute;tendues »</a></li>
    </ul>
  </div>
</div>
<div id="breadcrumbs" class="clearfix">
  <ul class="breadcrumbs-container">
    <li><a href="index.html">PHP Manual</a></li>
    <li><a href="langref.html">R&eacute;f&eacute;rence du langage</a></li>
    <li>Les exceptions</li>
  </ul>
</div>
<div id="layout">
  <div id="layout-content"><div id="language.exceptions" class="chapter">
  <h1>Les exceptions</h1>
<h2>Sommaire</h2><ul class="chunklist chunklist_chapter"><li><a href="language.exceptions.extending.html">Exceptions &eacute;tendues</a></li></ul>


  

  <div class="simplesect" id="language.exceptions.introduction">
   <p class="para">
    PHP a une gestion des exceptions similaire à ce qu&#039;offrent les autres
    langages de programmation.
    Une exception peut être lancée (&quot;<a href="language.exceptions.html" class="link"><code class="literal">throw</code></a>&quot;) et attrapée
    (&quot;<a href="language.exceptions.html#language.exceptions.catch" class="link"><code class="literal">catch</code></a>&quot;) dans PHP. Le code devra être entouré
    d&#039;un bloc <a href="language.exceptions.html" class="link"><code class="literal">try</code></a> pour faciliter la saisie d&#039;une exception
    potentielle. Chaque <a href="language.exceptions.html" class="link"><code class="literal">try</code></a> doit avoir au moins
    un bloc <a href="language.exceptions.html#language.exceptions.catch" class="link"><code class="literal">catch</code></a> ou <a href="language.exceptions.html#language.exceptions.finally" class="link"><code class="literal">finally</code></a> correspondant.
   </p>

   <p class="para">
    L&#039;objet lancé doit être une instance de la classe
    <a href="class.exception.html" class="classname">Exception</a> ou d&#039;une sous-classe de la classe
    <a href="class.exception.html" class="classname">Exception</a>. Tenter de lancer un objet qui ne
    correspond pas à cela résultera en une erreur fatale émise par PHP.
   </p>
  </div>

  <div class="simplesect" id="language.exceptions.catch">
   <h3 class="title"><code class="literal">catch</code></h3>
   <p class="para">
    Plusieurs blocs <a href="language.exceptions.html#language.exceptions.catch" class="link"><code class="literal">catch</code></a> peuvent être utilisés pour attraper différentes
    classes d&#039;exceptions. L&#039;exécution normale (lorsqu&#039;aucune exception n&#039;est lancée
    dans le bloc <a href="language.exceptions.html" class="link"><code class="literal">try</code></a>) continue après le dernier
    bloc <a href="language.exceptions.html#language.exceptions.catch" class="link"><code class="literal">catch</code></a> défini dans la séquence. Les exceptions
    peuvent être lancées (ou relancées) dans un bloc <a href="language.exceptions.html#language.exceptions.catch" class="link"><code class="literal">catch</code></a>.
   </p>
   <p class="para">
    Lorsqu&#039;une exception est lancée, le code suivant le traitement ne sera pas
    exécuté et PHP tentera de trouver le premier bloc <a href="language.exceptions.html#language.exceptions.catch" class="link"><code class="literal">catch</code></a> correspondant.
    Si une exception n&#039;est pas attrapée, une erreur fatale issue de PHP sera
    envoyée avec un message &quot;<code class="literal">Uncaught Exception ...</code>&quot; 
    indiquant que l&#039;exception n&#039;a pu être attrapée à  moins qu&#039;un gestionnaire 
    d&#039;exceptions ne soit défini avec la fonction
    <span class="function"><a href="function.set-exception-handler.html" class="function">set_exception_handler()</a></span>.
   </p>
   <p class="para">
    Depuis PHP 7.1, un block <a href="language.exceptions.html#language.exceptions.catch" class="link"><code class="literal">catch</code></a> peut spécifier plusieurs exceptions à 
    l&#039;aide du caratère pipe (<code class="literal">|</code>). Ceci est utile lorsque 
    différentes exceptions de hiérarchies de classes différentes sont traitées 
    de la même manière.
   </p>
  </div>

  <div class="simplesect" id="language.exceptions.finally">
   <h3 class="title"><code class="literal">finally</code></h3>
   <p class="para">
    En PHP 5.5 et suivant, un bloc <a href="language.exceptions.html#language.exceptions.finally" class="link"><code class="literal">finally</code></a> peut aussi être
    spécifié après des blocs <a href="language.exceptions.html#language.exceptions.catch" class="link"><code class="literal">catch</code></a>. Le code à l&#039;intérieur
    du bloc <a href="language.exceptions.html#language.exceptions.finally" class="link"><code class="literal">finally</code></a> sera toujours exécuté après les blocs
    <a href="language.exceptions.html" class="link"><code class="literal">try</code></a> et <a href="language.exceptions.html#language.exceptions.catch" class="link"><code class="literal">catch</code></a>, indépendament du fait qu&#039;une
    exception a été lancée, avant de continuer l&#039;exécution normale.
   </p>
   <p class="para">
    Une intéraction notable est entre un bloc <a href="language.exceptions.html#language.exceptions.finally" class="link"><code class="literal">finally</code></a> et une déclaration
    <a href="function.return.html" class="link"><code class="literal">return</code></a>.
    Si une déclaration <a href="function.return.html" class="link"><code class="literal">return</code></a> est rencontrée à l&#039;intérieur des blocs <a href="language.exceptions.html" class="link"><code class="literal">try</code></a>
    ou <a href="language.exceptions.html#language.exceptions.catch" class="link"><code class="literal">catch</code></a>, le bloc <a href="language.exceptions.html#language.exceptions.finally" class="link"><code class="literal">finally</code></a> sera quand même exécuté. Deplus,
    la déclaration <a href="function.return.html" class="link"><code class="literal">return</code></a> est évaluée quand elle est rencontrée, mais le
    résultat sera retourné après le bloc <a href="language.exceptions.html#language.exceptions.finally" class="link"><code class="literal">finally</code></a> soit exécuté.
    Additionellement, si le bloc <a href="language.exceptions.html#language.exceptions.finally" class="link"><code class="literal">finally</code></a> contient aussi une déclaration
    <a href="function.return.html" class="link"><code class="literal">return</code></a> la valeur du bloc <a href="language.exceptions.html#language.exceptions.finally" class="link"><code class="literal">finally</code></a> est retournée.
   </p>
  </div>

  <div class="simplesect" id="language.exceptions.notes">
   <h3 class="title">Notes</h3>

   <blockquote class="note"><p><strong class="note">Note</strong>: 
    <p class="para">
     Les fonctions internes de PHP utilisent principalement l&#039;
     <a href="errorfunc.configuration.html#ini.error-reporting" class="link">Error reporting</a>, seules les extensions 
     <a href="language.oop5.html" class="link">orientées objet</a>
     utilisent les exceptions. Quoiqu&#039;il en soit, des erreurs peuvent facilement être traduites en 
     exceptions avec <a href="class.errorexception.html" class="link">ErrorException</a>.
    </p>
   </p></blockquote>
   <div class="tip"><strong class="tip">Astuce</strong>
    <p class="para">
     La <a href="intro.spl.html" class="link">bibliothèque standard PHP (SPL)</a> fournit
     un bon nombre <a href="spl.exceptions.html" class="link">d&#039;exceptions additionnelles</a>.
    </p>
   </div>
  </div>

  <div class="simplesect" id="language.exceptions.examples">
   <h3 class="title">Exemples</h3>

   <div class="example" id="example-300">
    <p><strong>Exemple #3 Lancer une exception</strong></p>
    <div class="example-contents">
<div class="phpcode"><code><span style="color: #000000">
<span style="color: #0000BB">&lt;?php<br /></span><span style="color: #007700">function&nbsp;</span><span style="color: #0000BB">inverse</span><span style="color: #007700">(</span><span style="color: #0000BB">$x</span><span style="color: #007700">)&nbsp;{<br />&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(!</span><span style="color: #0000BB">$x</span><span style="color: #007700">)&nbsp;{<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;throw&nbsp;new&nbsp;</span><span style="color: #0000BB">Exception</span><span style="color: #007700">(</span><span style="color: #DD0000">'Division&nbsp;par&nbsp;zéro.'</span><span style="color: #007700">);<br />&nbsp;&nbsp;&nbsp;&nbsp;}<br />&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;</span><span style="color: #0000BB">1</span><span style="color: #007700">/</span><span style="color: #0000BB">$x</span><span style="color: #007700">;<br />}<br /><br />try&nbsp;{<br />&nbsp;&nbsp;&nbsp;&nbsp;echo&nbsp;</span><span style="color: #0000BB">inverse</span><span style="color: #007700">(</span><span style="color: #0000BB">5</span><span style="color: #007700">)&nbsp;.&nbsp;</span><span style="color: #DD0000">"\n"</span><span style="color: #007700">;<br />&nbsp;&nbsp;&nbsp;&nbsp;echo&nbsp;</span><span style="color: #0000BB">inverse</span><span style="color: #007700">(</span><span style="color: #0000BB">0</span><span style="color: #007700">)&nbsp;.&nbsp;</span><span style="color: #DD0000">"\n"</span><span style="color: #007700">;<br />}&nbsp;catch&nbsp;(</span><span style="color: #0000BB">Exception&nbsp;$e</span><span style="color: #007700">)&nbsp;{<br />&nbsp;&nbsp;&nbsp;&nbsp;echo&nbsp;</span><span style="color: #DD0000">'Exception&nbsp;reçue&nbsp;:&nbsp;'</span><span style="color: #007700">,&nbsp;&nbsp;</span><span style="color: #0000BB">$e</span><span style="color: #007700">-&gt;</span><span style="color: #0000BB">getMessage</span><span style="color: #007700">(),&nbsp;</span><span style="color: #DD0000">"\n"</span><span style="color: #007700">;<br />}<br /><br /></span><span style="color: #FF8000">//&nbsp;Continue&nbsp;execution<br /></span><span style="color: #007700">echo&nbsp;</span><span style="color: #DD0000">"Bonjour&nbsp;le&nbsp;monde&nbsp;!\n"</span><span style="color: #007700">;<br /></span><span style="color: #0000BB">?&gt;</span>
</span>
</code></div>
    </div>

    <div class="example-contents"><p>L&#039;exemple ci-dessus va afficher :</p></div>
    <div class="example-contents screen">
<div class="cdata"><pre>
0.2
Exception reçue : Division par zéro.
Bonjour le monde !
</pre></div>
    </div>
   </div>
   <div class="example" id="example-301">
    <p><strong>Exemple #4 Gestion de l&#039;exception avec un bloc <a href="language.exceptions.html#language.exceptions.finally" class="link"><code class="literal">finally</code></a></strong></p>
    <div class="example-contents">
<div class="phpcode"><code><span style="color: #000000">
<span style="color: #0000BB">&lt;?php<br /></span><span style="color: #007700">function&nbsp;</span><span style="color: #0000BB">inverse</span><span style="color: #007700">(</span><span style="color: #0000BB">$x</span><span style="color: #007700">)&nbsp;{<br />&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(!</span><span style="color: #0000BB">$x</span><span style="color: #007700">)&nbsp;{<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;throw&nbsp;new&nbsp;</span><span style="color: #0000BB">Exception</span><span style="color: #007700">(</span><span style="color: #DD0000">'Division&nbsp;par&nbsp;zéro.'</span><span style="color: #007700">);<br />&nbsp;&nbsp;&nbsp;&nbsp;}<br />&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;</span><span style="color: #0000BB">1</span><span style="color: #007700">/</span><span style="color: #0000BB">$x</span><span style="color: #007700">;<br />}<br /><br />try&nbsp;{<br />&nbsp;&nbsp;&nbsp;&nbsp;echo&nbsp;</span><span style="color: #0000BB">inverse</span><span style="color: #007700">(</span><span style="color: #0000BB">5</span><span style="color: #007700">)&nbsp;.&nbsp;</span><span style="color: #DD0000">"\n"</span><span style="color: #007700">;<br />}&nbsp;catch&nbsp;(</span><span style="color: #0000BB">Exception&nbsp;$e</span><span style="color: #007700">)&nbsp;{<br />&nbsp;&nbsp;&nbsp;&nbsp;echo&nbsp;</span><span style="color: #DD0000">'Exception&nbsp;reçue&nbsp;:&nbsp;'</span><span style="color: #007700">,&nbsp;&nbsp;</span><span style="color: #0000BB">$e</span><span style="color: #007700">-&gt;</span><span style="color: #0000BB">getMessage</span><span style="color: #007700">(),&nbsp;</span><span style="color: #DD0000">"\n"</span><span style="color: #007700">;<br />}&nbsp;finally&nbsp;{<br />&nbsp;&nbsp;&nbsp;&nbsp;echo&nbsp;</span><span style="color: #DD0000">"Première&nbsp;fin.\n"</span><span style="color: #007700">;<br />}<br /><br />try&nbsp;{<br />&nbsp;&nbsp;&nbsp;&nbsp;echo&nbsp;</span><span style="color: #0000BB">inverse</span><span style="color: #007700">(</span><span style="color: #0000BB">0</span><span style="color: #007700">)&nbsp;.&nbsp;</span><span style="color: #DD0000">"\n"</span><span style="color: #007700">;<br />}&nbsp;catch&nbsp;(</span><span style="color: #0000BB">Exception&nbsp;$e</span><span style="color: #007700">)&nbsp;{<br />&nbsp;&nbsp;&nbsp;&nbsp;echo&nbsp;</span><span style="color: #DD0000">'Exception&nbsp;reçue&nbsp;:&nbsp;'</span><span style="color: #007700">,&nbsp;&nbsp;</span><span style="color: #0000BB">$e</span><span style="color: #007700">-&gt;</span><span style="color: #0000BB">getMessage</span><span style="color: #007700">(),&nbsp;</span><span style="color: #DD0000">"\n"</span><span style="color: #007700">;<br />}&nbsp;finally&nbsp;{<br />&nbsp;&nbsp;&nbsp;&nbsp;echo&nbsp;</span><span style="color: #DD0000">"Seconde&nbsp;fin.\n"</span><span style="color: #007700">;<br />}<br /><br /></span><span style="color: #FF8000">//&nbsp;On&nbsp;continue&nbsp;l'exécution<br /></span><span style="color: #007700">echo&nbsp;</span><span style="color: #DD0000">"Bonjour&nbsp;le&nbsp;monde&nbsp;!\n"</span><span style="color: #007700">;<br /></span><span style="color: #0000BB">?&gt;</span>
</span>
</code></div>
    </div>

    <div class="example-contents"><p>L&#039;exemple ci-dessus va afficher :</p></div>
    <div class="example-contents screen">
<div class="cdata"><pre>
0.2
Première fin.
Exception reçue : Division par zéro.
Seconde fin.
Bonjour le monde !
</pre></div>
    </div>
   </div>
   <div class="example" id="example-302">
    <p><strong>Exemple #5 Intéraction entre le bloc <a href="language.exceptions.html#language.exceptions.finally" class="link"><code class="literal">finally</code></a> et <a href="function.return.html" class="link"><code class="literal">return</code></a></strong></p>
    <div class="example-contents">
<div class="phpcode"><code><span style="color: #000000">
<span style="color: #0000BB">&lt;?php<br /><br /></span><span style="color: #007700">function&nbsp;</span><span style="color: #0000BB">test</span><span style="color: #007700">()&nbsp;{<br />&nbsp;&nbsp;&nbsp;&nbsp;try&nbsp;{<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;throw&nbsp;new&nbsp;</span><span style="color: #0000BB">Exception</span><span style="color: #007700">(</span><span style="color: #DD0000">'foo'</span><span style="color: #007700">);<br />&nbsp;&nbsp;&nbsp;&nbsp;}&nbsp;catch&nbsp;(</span><span style="color: #0000BB">Exception&nbsp;$e</span><span style="color: #007700">)&nbsp;{<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;</span><span style="color: #DD0000">'catch'</span><span style="color: #007700">;<br />&nbsp;&nbsp;&nbsp;&nbsp;}&nbsp;finally&nbsp;{<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;</span><span style="color: #DD0000">'finally'</span><span style="color: #007700">;<br />&nbsp;&nbsp;&nbsp;&nbsp;}<br />}<br /><br />echo&nbsp;</span><span style="color: #0000BB">test</span><span style="color: #007700">();<br /></span><span style="color: #0000BB">?&gt;</span>
</span>
</code></div>
    </div>

    <div class="example-contents"><p>L&#039;exemple ci-dessus va afficher :</p></div>
    <div class="example-contents screen">
<div class="cdata"><pre>
finally
</pre></div>
    </div>
   </div>
   <div class="example" id="example-303">
    <p><strong>Exemple #6 Héritage d&#039;une exception</strong></p>
    <div class="example-contents">
<div class="phpcode"><code><span style="color: #000000">
<span style="color: #0000BB">&lt;?php<br /><br /></span><span style="color: #007700">class&nbsp;</span><span style="color: #0000BB">MyException&nbsp;</span><span style="color: #007700">extends&nbsp;</span><span style="color: #0000BB">Exception&nbsp;</span><span style="color: #007700">{&nbsp;}<br /><br />class&nbsp;</span><span style="color: #0000BB">Test&nbsp;</span><span style="color: #007700">{<br />&nbsp;&nbsp;&nbsp;&nbsp;public&nbsp;function&nbsp;</span><span style="color: #0000BB">testing</span><span style="color: #007700">()&nbsp;{<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;try&nbsp;{<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;try&nbsp;{<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;throw&nbsp;new&nbsp;</span><span style="color: #0000BB">MyException</span><span style="color: #007700">(</span><span style="color: #DD0000">'foo!'</span><span style="color: #007700">);<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}&nbsp;catch&nbsp;(</span><span style="color: #0000BB">MyException&nbsp;$e</span><span style="color: #007700">)&nbsp;{<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #FF8000">//&nbsp;on&nbsp;la&nbsp;relance<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #007700">throw&nbsp;</span><span style="color: #0000BB">$e</span><span style="color: #007700">;<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}&nbsp;catch&nbsp;(</span><span style="color: #0000BB">Exception&nbsp;$e</span><span style="color: #007700">)&nbsp;{<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #0000BB">var_dump</span><span style="color: #007700">(</span><span style="color: #0000BB">$e</span><span style="color: #007700">-&gt;</span><span style="color: #0000BB">getMessage</span><span style="color: #007700">());<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br />&nbsp;&nbsp;&nbsp;&nbsp;}<br />}<br /><br /></span><span style="color: #0000BB">$foo&nbsp;</span><span style="color: #007700">=&nbsp;new&nbsp;</span><span style="color: #0000BB">Test</span><span style="color: #007700">;<br /></span><span style="color: #0000BB">$foo</span><span style="color: #007700">-&gt;</span><span style="color: #0000BB">testing</span><span style="color: #007700">();<br /><br /></span><span style="color: #0000BB">?&gt;</span>
</span>
</code></div>
    </div>

    <div class="example-contents"><p>L&#039;exemple ci-dessus va afficher :</p></div>
    <div class="example-contents screen">
<div class="cdata"><pre>
string(4) &quot;foo!&quot;
</pre></div>
    </div>
   </div>
   <div class="example" id="example-304">
    <p><strong>Exemple #7 Gestion des exceptions de capture multiple</strong></p>
    <div class="example-contents">
<div class="phpcode"><code><span style="color: #000000">
<span style="color: #0000BB">&lt;?php<br /><br /></span><span style="color: #007700">class&nbsp;</span><span style="color: #0000BB">MyException&nbsp;</span><span style="color: #007700">extends&nbsp;</span><span style="color: #0000BB">Exception&nbsp;</span><span style="color: #007700">{&nbsp;}<br /><br />class&nbsp;</span><span style="color: #0000BB">MyOtherException&nbsp;</span><span style="color: #007700">extends&nbsp;</span><span style="color: #0000BB">Exception&nbsp;</span><span style="color: #007700">{&nbsp;}<br /><br />class&nbsp;</span><span style="color: #0000BB">Test&nbsp;</span><span style="color: #007700">{<br />&nbsp;&nbsp;&nbsp;&nbsp;public&nbsp;function&nbsp;</span><span style="color: #0000BB">testing</span><span style="color: #007700">()&nbsp;{<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;try&nbsp;{<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;throw&nbsp;new&nbsp;</span><span style="color: #0000BB">MyException</span><span style="color: #007700">();<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}&nbsp;catch&nbsp;(</span><span style="color: #0000BB">MyException&nbsp;</span><span style="color: #007700">|&nbsp;</span><span style="color: #0000BB">MyOtherException&nbsp;$e</span><span style="color: #007700">)&nbsp;{<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #0000BB">var_dump</span><span style="color: #007700">(</span><span style="color: #0000BB">get_class</span><span style="color: #007700">(</span><span style="color: #0000BB">$e</span><span style="color: #007700">));<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br />&nbsp;&nbsp;&nbsp;&nbsp;}<br />}<br /><br /></span><span style="color: #0000BB">$foo&nbsp;</span><span style="color: #007700">=&nbsp;new&nbsp;</span><span style="color: #0000BB">Test</span><span style="color: #007700">;<br /></span><span style="color: #0000BB">$foo</span><span style="color: #007700">-&gt;</span><span style="color: #0000BB">testing</span><span style="color: #007700">();<br /><br /></span><span style="color: #0000BB">?&gt;</span>
</span>
</code></div>
    </div>

    <div class="example-contents"><p>L&#039;exemple ci-dessus va afficher :</p></div>
    <div class="example-contents screen">
<div class="cdata"><pre>
string(11) &quot;MyException&quot;
</pre></div>
    </div>
   </div>
  </div>
 </div>
</div></div></body></html>