<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
 <head>
  <meta http-equiv="content-type" content="text/html; charset=UTF-8">
  <title>R&eacute;cup&egrave;re la cause d'une exception</title>
<link media="all" rel="stylesheet" type="text/css" href="styles/03e73060321a0a848018724a6c83de7f-theme-base.css" />
<link media="all" rel="stylesheet" type="text/css" href="styles/03e73060321a0a848018724a6c83de7f-theme-medium.css" />

 </head>
 <body class="docs"><div class="navbar navbar-fixed-top">
  <div class="navbar-inner clearfix">
    <ul class="nav" style="width: 100%">
      <li style="float: left;"><a href="sdo-dataobject.gettypenamespaceuri.html">« SDO_DataObject::getTypeNamespaceURI</a></li>
      <li style="float: right;"><a href="sdo-list.insert.html">SDO_List::insert »</a></li>
    </ul>
  </div>
</div>
<div id="breadcrumbs" class="clearfix">
  <ul class="breadcrumbs-container">
    <li><a href="index.html">PHP Manual</a></li>
    <li><a href="ref.sdo.html">Fonctions SDO</a></li>
    <li>R&eacute;cup&egrave;re la cause d'une exception</li>
  </ul>
</div>
<div id="layout">
  <div id="layout-content"><div id="sdo-exception.getcause" class="refentry">
 <div class="refnamediv">
  <h1 class="refname">SDO_Exception::getCause</h1>
  <p class="verinfo">(^)</p><p class="refpurpose"><span class="refname">SDO_Exception::getCause</span> &mdash; <span class="dc-title">
   Récupère la cause d&#039;une exception
  </span></p>

 </div>
 <div class="refsect1 description" id="refsect1-sdo-exception.getcause-description">
  <h3 class="title">Description</h3>
  <div class="methodsynopsis dc-description">
   <span class="methodname"><strong>SDO_Exception::getCause</strong></span>
    ( <span class="methodparam">void</span>
   ) : <span class="type"><a href="language.pseudo-types.html#language.types.mixed" class="type mixed">mixed</a></span></div>


  <div class="warning"><strong class="warning">Avertissement</strong><p class="simpara">
 Cette fonction est <em class="emphasis">EXPERIMENTALE</em>. Le comportement de cette fonction, son nom, et toute la
 documentation autour de cette fonction peut changer sans préavis dans une prochaine version de PHP.
 Cette fonction doit être utilisée à vos risques et périls.
</p></div>

  <p class="para">
   Retourne la cause de cette exception ou <strong><code>NULL</code></strong> si la cause est inexistante
   ou inconnue. Normalement, la cause sera un objet SDO_CPPException, qui peut
   être utilisé pour obtenir des informations de diagnostique additionnelles.
  </p>

 </div>

 <div class="refsect1 parameters" id="refsect1-sdo-exception.getcause-parameters">
  <h3 class="title">Liste de paramètres</h3>
  <p class="para">
   Aucun.
  </p>
 </div>

 <div class="refsect1 returnvalues" id="refsect1-sdo-exception.getcause-returnvalues">
  <h3 class="title">Valeurs de retour</h3>
  <p class="para">
   Retourne la cause de cette exception ou <strong><code>NULL</code></strong> si la cause est inexistante
   ou inconnue.
  </p>
 </div>

 
</div></div></div></body></html>